spring:
  application:
    name: Notebook

  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:notes}
      username: admin
      password: password
      authentication-database: admin
